# docker-compose.yml (repo root)
name: cloudy

services:
  # ---------- DEV ----------
  api-dev:
    build:
      context: .
      target: dev
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__DefaultConnection: ${DB_CONNSTRING}
    volumes:
      - ./:/src
    depends_on:
      db-dev:
        condition: service_healthy
    ports:
      - "5170:8080"
    profiles: ["dev"]

  db-dev:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"   # host -> container (for PGAdmin/psql)
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 10
    profiles: ["dev"]

  # ---------- PROD ----------
  api-prod:
    build:
      context: .
      target: prod
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__DefaultConnection: ${DB_CONNSTRING}
      PROD_GUARD: ${PROD_GUARD}
    depends_on:
      db-prod:
        condition: service_healthy
    read_only: true
    tmpfs:
      - /tmp
    restart: always
    profiles: ["prod"]

  db-prod:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgdata-prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
    profiles: ["prod"]

volumes:
  pgdata-dev:
  pgdata-prod:


